name: Final Android Task
on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run tests
        run: run test